language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

after_script:
  - cd ./dist
  - git init 
  - git config user.name "BiYuqi"
  - git config user.email "biyuqiwan@163.com"
  - git add .
  - git commit -m "Deployed by travis-ci"
  - git push --force --quiet "https://${WEBPACK_SEED}@${GH_REF}" master:gh-pages

branches:
  only:
  # 暂时关闭travis-ci自动部署，因为gitpage有二级目录，导致部署后警台资源路径不对
  # 等后续脚手架开发稳定后，单独开分支做预览
    - feature
env:
 global:
   - GH_REF: github.com/BiYuqi/webpack-seed.git